import { Injectable } from '@angular/core';

/**
 * Controls time for {@link LumberjackLog#createdAt} timestamps generated by a
 * {@link LumberjackLogger} subclass.
 */
@Injectable({
  providedIn: 'root',
})
export class LumberjackTimeService {
  getUnixEpochTicks(): number {
    return Date.now();
  }
}
